title: Black Rain Security
email: 
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "blackrainsecurity.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
  nav_pages:
    - index.markdown
    - about.markdown
    - clients.markdown
    - solutions.markdown
    - contact.markdown

logo: /assets/images/logo.png
